/*
<a href="lab/bg/sky-sunset/"><div class="nybtn--labEmoji">🌅🌤️✨</div></a>
<a href="lab/btns/btn-types/"><div class="nybtn--labEmoji">🔘🟦</div></a>
<a href="lab/btns/do-btns/"><div class="nybtn--labEmoji">🎨🟠🟣</div></a>
<a href="lab/building/3d-rooms/"><div class="nybtn--labEmoji">🏠📦🧊</div></a>
<a href="lab/building/blocks/"><div class="nybtn--labEmoji">🧱📦</div></a>
<a href="lab/building/brick-wall/bricks.html"><div class="nybtn--labEmoji">🧱🔳</div></a>
<a href="lab/building/checkerboard/"><div class="nybtn--labEmoji">🏁</div></a>
<a href="lab/building/daisy/"><div class="nybtn--labEmoji">🌼</div></a>
<a href="lab/building/svg-block/"><div class="nybtn--labEmoji">🧊📐</div></a>
<a href="lab/building/tail-wind/index.html"><div class="nybtn--labEmoji">🌬️💨</div></a>
<a href="lab/building/tile-patterns-02/index.html"><div class="nybtn--labEmoji">🧩🔷</div></a>
<a href="lab/building/tile-wf/"><div class="nybtn--labEmoji">🔳🌱🌊</div></a>
<a href="lab/building/wave-blocks/"><div class="nybtn--labEmoji">🌊📦🧊</div></a>
<a href="lab/canvas/brush/"><div class="nybtn--labEmoji">🖌️🎨</div></a>
<a href="lab/canvas/canvas-map.html"><div class="nybtn--labEmoji">🖼️📜</div></a>
<a href="lab/canvas/chasing/"><div class="nybtn--labEmoji">🖱️💨🔄</div></a>
<a href="lab/canvas/cloud-brush/"><div class="nybtn--labEmoji">☁️🖌️</div></a>
<a href="lab/canvas/fire-circles/"><div class="nybtn--labEmoji">🔥🖱️</div></a>
<a href="lab/canvas/firesphere/circle-p.html"><div class="nybtn--labEmoji">🔥⬇️</div></a>
<a href="lab/canvas/firesphere/circle-p2.html"><div class="nybtn--labEmoji">🔥➡️</div></a>
<a href="lab/canvas/firesphere/liquid-fire--nds-01.html"><div class="nybtn--labEmoji">🔥🧪</div></a>
<a href="lab/canvas/firesphere/liquid-fire--nds-03.html"><div class="nybtn--labEmoji">🔥✨</div></a>
<a href="lab/canvas/firesphere/liquid-fire--nds-04.html"><div class="nybtn--labEmoji">🔥🌫️</div></a>
<a href="lab/canvas/fireworks/"><div class="nybtn--labEmoji">🎆🌌</div></a>
<a href="lab/canvas/fluid/"><div class="nybtn--labEmoji">🌊💧🖱️</div></a>
<a href="lab/canvas/liquid-particles/"><div class="nybtn--labEmoji">💧🎨</div></a>
<a href="lab/canvas/moving/"><div class="nybtn--labEmoji">🎮❌👉📲</div></a>
<a href="lab/canvas/orbit-set/"><div class="nybtn--labEmoji">🌀⚙️</div></a>
<a href="lab/canvas/orbit/"><div class="nybtn--labEmoji">⚛️⚡⬇️</div></a>
<a href="lab/canvas/particle-collision-in-sectors/"><div class="nybtn--labEmoji">💥🧭</div></a>
<a href="lab/canvas/particle-collision/"><div class="nybtn--labEmoji">💥📊</div></a>
<a href="lab/canvas/plasma/"><div class="nybtn--labEmoji">⚡🌩️</div></a>
<a href="lab/canvas/rainbow-brush/"><div class="nybtn--labEmoji">🌈🖌️</div></a>
<a href="lab/canvas/rainbow-cloud-brush/"><div class="nybtn--labEmoji">🌈☁️🖌️</div></a>
<a href="lab/canvas/re-experiment/re-exp-04b.html"><div class="nybtn--labEmoji">🎆🌌</div></a>
<a href="lab/canvas/rules-part/mouse-nds-05.html"><div class="nybtn--labEmoji">🖱️💨</div></a>
<a href="lab/canvas/spell-effect/"><div class="nybtn--labEmoji">✨🧙‍♂️📿</div></a>
<a href="lab/canvas/view-p/axis-view.html"><div class="nybtn--labEmoji">🎥📐👉📲</div></a>
<a href="lab/canvas/waveave/Waveave.html"><div class="nybtn--labEmoji">🌈〰</div></a>
<a href="lab/cards/card-bg/"><div class="nybtn--labEmoji">🎴🃏</div></a>
<a href="lab/cards/card-designs/"><div class="nybtn--labEmoji">🃏🎨</div></a>
<a href="lab/color/color-curves/index.html"><div class="nybtn--labEmoji">🎨📈</div></a>
<a href="lab/color/color-palette/"><div class="nybtn--labEmoji">🎨🟦🟥</div></a>
<a href="lab/color/color-random/"><div class="nybtn--labEmoji">🎨🎲</div></a>
<a href="lab/color/color-sequence/"><div class="nybtn--labEmoji">🟦➡️🟥</div></a>
<a href="lab/color/color-symmetry/"><div class="nybtn--labEmoji">🟩🔁</div></a>
<a href="lab/cube/cube-ant-maze/"><div class="nybtn--labEmoji">🧊🐜🌀</div></a>
<a href="lab/cube/cube-paths/index.html"><div class="nybtn--labEmoji">🧊🎨</div></a>
<a href="lab/designs/bg-up/"><div class="nybtn--labEmoji">🌄🔳</div></a>
<a href="lab/designs/gg-ous/"><div class="nybtn--labEmoji">🌪️✨</div></a>
<a href="lab/designs/myst-box/"><div class="nybtn--labEmoji">☁️📦</div></a>
<a href="lab/designs/turbulence-filter/"><div class="nybtn--labEmoji">🌪️🧪</div></a>
<a href="lab/dev/build/grid.html"><div class="nybtn--labEmoji">🔲🏗️</div></a>
<a href="lab/dev/variant-dev/"><div class="nybtn--labEmoji">🌪️🎨</div></a>
<a href="lab/eqs/draw-eq/"><div class="nybtn--labEmoji">🧭🔳</div></a>
<a href="lab/eqs/exp/"><div class="nybtn--labEmoji">💧🌐</div></a>
<a href="lab/eqs/noise-field/noise.html"><div class="nybtn--labEmoji">📡🔉</div></a>
<a href="lab/eqs/ray-tracing-exp/index--nds-01.html"><div class="nybtn--labEmoji">🌈🔦🎨</div></a>
<a href="lab/eqs/ray-tracing/"><div class="nybtn--labEmoji">🔦🌊</div></a>
<a href="lab/eqs/ray-tracing/simplify-nds-02.html"><div class="nybtn--labEmoji">🔦🌊🎨</div></a>
<a href="lab/eqs/ray-tracing/simplify-rgb.html"><div class="nybtn--labEmoji">🔴🟢🔵💠</div></a>
<a href="lab/eqs/two-ripples/"><div class="nybtn--labEmoji">💧💧</div></a>
<a href="lab/eqs/wave-field/index.html"><div class="nybtn--labEmoji">🌊💫</div></a>
<a href="lab/eval/calc-eval/"><div class="nybtn--labEmoji">🎲➡️</div></a>
<a href="lab/eval/grid-eval/"><div class="nybtn--labEmoji">💻</div></a>
<a href="lab/event/intersection-observer/"><div class="nybtn--labEmoji">👁️📐</div></a>
<a href="lab/event/mouse-move/index.html"><div class="nybtn--labEmoji">🖱️👣</div></a>
<a href="lab/event/mouse-move/touch.html"><div class="nybtn--labEmoji">👉🖌️</div></a>
<a href="lab/exp/creature-randomizer/"><div class="nybtn--labEmoji">🧬👾</div></a>
<a href="lab/exp/creature-randomizer/creature-randomizer.html"><div class="nybtn--labEmoji">🧬👾👾</div></a>
<a href="lab/exp/dome-animation/"><div class="nybtn--labEmoji">🏛️🎞️</div></a>
<a href="lab/exp/drag-rotate/"><div class="nybtn--labEmoji">👆🔄</div></a>
<a href="lab/exp/flow-arrows/"><div class="nybtn--labEmoji">🌬️🍃</div></a>
<a href="lab/exp/hex-grid/"><div class="nybtn--labEmoji">⬡🌀</div></a>
<a href="lab/exp/liquid/"><div class="nybtn--labEmoji">💧🌊</div></a>
<a href="lab/exp/randsphere/"><div class="nybtn--labEmoji">🌐🎲</div></a>
<a href="lab/exp/window/check.html"><div class="nybtn--labEmoji">🖥️📱✔️</div></a>
<a href="lab/fonts/selected-fonts/"><div class="nybtn--labEmoji">🔤📝</div></a>
<a href="lab/games/paths/"><div class="nybtn--labEmoji">🛣️🧭</div></a>
<a href="lab/graphs/spidergraph/"><div class="nybtn--labEmoji">🕸</div></a>
<a href="lab/grid/mat-dist/"><div class="nybtn--labEmoji">🟩🧮</div></a>
<a href="lab/holonomy/holonomy-key-controllers/"><div class="nybtn--labEmoji">🔑🌀</div></a>
<a href="lab/holonomy/rotation-rings/rings.html"><div class="nybtn--labEmoji">🔄⭕</div></a>
<a href="lab/keyevents/keydown/"><div class="nybtn--labEmoji">⌨️⬇️</div></a>
<a href="lab/layout/bar-graphs/"><div class="nybtn--labEmoji">📊📈</div></a>
<a href="lab/layout/glowing-chip/"><div class="nybtn--labEmoji">💡🔘</div></a>
<a href="lab/layout/graph-curve/index.html"><div class="nybtn--labEmoji">📈〰️</div></a>
<a href="lab/layout/layout-3d/"><div class="nybtn--labEmoji">🧊📰</div></a>
<a href="lab/layout/loading-circles/"><div class="nybtn--labEmoji">🔄⭕</div></a>
<a href="lab/layout/magic-store/"><div class="nybtn--labEmoji">✨🏬🛒</div></a>
<a href="lab/layout/neumorphic-design/"><div class="nybtn--labEmoji">🔘💠</div></a>
<a href="lab/layout/neumorphic-recreate/"><div class="nybtn--labEmoji">🔘</div></a>
<a href="lab/layout/tile-layout/"><div class="nybtn--labEmoji">💠</div></a>
<a href="lab/layout/ui-icons/"><div class="nybtn--labEmoji">🖼️🧩</div></a>
<a href="lab/math/quick-random/"><div class="nybtn--labEmoji">🎲⚡</div></a>
<a href="lab/nds/glowing-dots/"><div class="nybtn--labEmoji">✨🔵</div></a>
<a href="lab/nds/nds-08/"><div class="nybtn--labEmoji">🌌💠</div></a>
<a href="lab/nyte/nyte-logo/"><div class="nybtn--labEmoji">🌕</div></a>
<a href="lab/other/git-calendar/"><div class="nybtn--labEmoji">📅🟩</div></a>
<a href="lab/particle-rules/axis-rotation/axis-2.html"><div class="nybtn--labEmoji">🔄📐</div></a>
<a href="lab/particle-rules/fire-01/fire.html"><div class="nybtn--labEmoji">🔥🎆</div></a>
<a href="lab/particle-rules/fire/fire.html"><div class="nybtn--labEmoji">🔥</div></a>
<a href="lab/particle-rules/fires/"><div class="nybtn--labEmoji">🔥🔥🌈</div></a>
<a href="lab/particle-rules/fluid-grid/fluid-grid.html"><div class="nybtn--labEmoji">🌊🔳</div></a>
<a href="lab/particle-rules/fuse/index.html"><div class="nybtn--labEmoji">✨⚡</div></a>
<a href="lab/particle-rules/gravity/"><div class="nybtn--labEmoji">👑⬇️</div></a>
<a href="lab/particle-rules/particle-colors/"><div class="nybtn--labEmoji">🎨🌌</div></a>
<a href="lab/particle-rules/particle-tails/"><div class="nybtn--labEmoji">🌀🌌🌠</div></a>
<a href="lab/particle-rules/path/"><div class="nybtn--labEmoji">🌈🛣️</div></a>
<a href="lab/particle-rules/proximity/"><div class="nybtn--labEmoji">📏🤏</div></a>
<a href="lab/pattern-weaver/"><div class="nybtn--labEmoji">🧵🎨</div></a>
<a href="lab/puzzle/gear-tiles/"><div class="nybtn--labEmoji">⚙💠</div></a>
<a href="lab/recreate/coding-train-180/"><div class="nybtn--labEmoji">🏜️⬇️</div></a>
<a href="lab/recreate/kinetic-sculpture/"><div class="nybtn--labEmoji">⚙️🌀</div></a>
<a href="lab/recreate/patterns/rotating-pattern.html"><div class="nybtn--labEmoji">🌌</div></a>
<a href="lab/recreate/truchet-tiles/index"><div class="nybtn--labEmoji">🧩🔳</div></a>
<a href="lab/science-based-experiments/boiling/boil-attempt.html"><div class="nybtn--labEmoji">🔥♨️🎆</div></a>
<a href="lab/science-based-experiments/boiling/boiling.html"><div class="nybtn--labEmoji">🔥♨️🌈</div></a>
<a href="lab/science-based-experiments/buoyancy/"><div class="nybtn--labEmoji">⛵</div></a>
<a href="lab/science-based-experiments/whirl/"><div class="nybtn--labEmoji">🌌🌀</div></a>
<a href="lab/spells/arms-of-hadar/"><div class="nybtn--labEmoji">🐙👾🎆</div></a>
<a href="lab/spheres/dotsphere/"><div class="nybtn--labEmoji">⚪🌐</div></a>
<a href="lab/spheres/orbit/"><div class="nybtn--labEmoji">🪐🔄</div></a>
<a href="lab/stars/pulsing-sun/"><div class="nybtn--labEmoji">🔆🌞</div></a>
<a href="lab/svg/backgrounds/"><div class="nybtn--labEmoji">🖼️🌄</div></a>
<a href="lab/svg/cards/"><div class="nybtn--labEmoji">🃏📐</div></a>
<a href="lab/svg/cloud-exp-02/"><div class="nybtn--labEmoji">☁️🎞️</div></a>
<a href="lab/svg/items/"><div class="nybtn--labEmoji">📦</div></a>
<a href="lab/svg/sky/"><div class="nybtn--labEmoji">☁️🌙☁️</div></a>
<a href="lab/svg/sky/day-night-scroll.html"><div class="nybtn--labEmoji">🌞➡️🌙🚧</div></a>
<a href="lab/svg/sky/sky-cards.html"><div class="nybtn--labEmoji">☁️🌙☁️🎴</div></a>
<a href="lab/svg/sky/sky.html"><div class="nybtn--labEmoji">☁️🌙☁️🖥️</div></a>
<a href="lab/svg/wood/"><div class="nybtn--labEmoji">🪵📐</div></a>
<a href="lab/ttrpg/character-sheet/"><div class="nybtn--labEmoji">🎲📝</div></a>
<a href="lab/unknown/unknown-drive/unknown-element.html"><div class="nybtn--labEmoji">❓🧪</div></a>
<a href="lab/unknown/unknown-form/index--liquid-fire.html"><div class="nybtn--labEmoji">🔥💧</div></a>
<a href="lab/unknown/unknown-form/index--unknown-element-heat-color.html"><div class="nybtn--labEmoji">🧪❓🌡️</div></a>
<a href="lab/waves/curves/"><div class="nybtn--labEmoji">🌊〰️📊</div></a>
<a href="lab/waves/grid-waves-02/"><div class="nybtn--labEmoji">🔳🌊</div></a>
<a href="lab/xo/css-only/"><div class="nybtn--labEmoji">❌⭕🧩🎮</div></a>


*/